name: End-to-end tests
on: [push]

env:
  DATABASE_URL: ${{secrets.DEV_DATABASE_URL}}
  JWT_SECRET: ${{secrets.JWT_SECRET}}

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - run: npm ci && cd packages/prisma-schema && npx prisma generate && cd ../../
      - run: cd apps/web && npm run ci
